website/models.py
from . import db
from sqlalchemy.types import JSON

class queryData(db.Model):
    __tablename__ = "queryData"

    id = db.Column(db.Integer, primary_key=True)
    search = db.Column(db.String(150))
    abstract = db.Column(db.String(1000))
    year = db.Column(db.String(150))
    lemmas = db.Column (db.JSON)
    retrieved = db.Column(db.String(100))
    total = db.Column(db.String(100))

    def __repr__(self):
        return f"<queryData(id={self.id}, search='{self.search}', abstract='{self.abstract}', year={self.year}, lemmas={self.lemmas}, retrieved_abstracts={self.retrieved}, total_abstracts={self.total})>"

class compoundScoringData(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    search = db.Column(db.String(150))
    compound_term = db.Column(db.String(100))
    tfidf_score = db.Column(db.Float)

    def __repr__(self):
        return f"<compoundScoringData(id={self.id}, search='{self.search}', term='{self.compound_term}', tfidf_score={self.tfidf_score})>"
    
class featureScoringData(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    search = db.Column(db.String(150))
    feature_term = db.Column(db.String(100))
    tfidf_score = db.Column(db.Float)

    def __repr__(self):
        return f"<featureScoringData(id={self.id}, search='{self.search}', term='{self.feature_term}', tfidf_score={self.tfidf_score})>"
    
class associatedDiseases(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    search = db.Column(db.String(150))
    disease_term = db.Column(db.String(100))
    frequency = db.Column(db.Float)

    def __repr__(self):
        return f"<associatedDiseases(id={self.id}, search='{self.search}', disease_term='{self.disease_term}', frequency={self.frequency})>"
    
class cosineSimilarity(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    search = db.Column(db.String(150))
    term = db.Column(db.String(100))
    cosine_similarity = db.Column(db.Float)
    corpus = db.Column(db.String(150))

    def __repr__(self):
        return f"<cosineSimilarity(id={self.id}, search='{self.search}', term='{self.term}', cosine_similarity={self.cosine_similarity}, corpus={self.corpus})>"

website/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from os import path

db = SQLAlchemy()

def create_app():
    app = Flask(__name__)
    app.config['SQLALCHEMY_DATABASE_URI'] = "sqlite:///data.db"
    app.config['SECRET_KEY'] = "secret"
    db.init_app(app)

    from .views import views
    
    app.register_blueprint(views, url_prefix='/')

    with app.app_context():
        db.create_all()

    return app

website/views.py
from flask import Blueprint, render_template, request, session, url_for, redirect
from main import getLitData
from main import resetDatabase
from main import runWord2Vec
from main import protein_extactor
from main import generateDrugProfiles
from . import db
from .models import queryData
import json
import subprocess
import os
import sys

from website.models import queryData
from website.models import featureScoringData
from website.models import compoundScoringData
from website.models import associatedDiseases
from website.models import cosineSimilarity

from Drugs_Proteins.uniprot_api import protein_seq_main

parent_dir = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
sys.path.append(parent_dir)

repo_dir = os.path.dirname(os.path.abspath(__file__))  # Path to the current script
project_root = os.path.abspath(os.path.join(repo_dir, ".."))  # One level up to /drugsift
ssm_dta_dir = os.path.join(project_root, "SSM_DTA")  # Path to /drugsift/SSM_DTA

if ssm_dta_dir not in sys.path:  # Avoid duplicates
    sys.path.append(ssm_dta_dir)

from SSM_DTA.infer import run_inference
from SSM_DTA.preprocess.add_space import run_add_space
from SSM_DTA.preprocess.canonicalize import run_canonicalization
from SSM_DTA.preprocess.tokenize_re import run_tokenization

from Drugs_Proteins.pubchem_api import get_smiles_from_pubchem

current_dir = os.path.dirname(os.path.abspath(__file__))

views = Blueprint('views', __name__)

@views.route("/", methods=["POST", "GET"])
@views.route("/home", methods=["POST", "GET"])
def home():
    with open(os.path.join(current_dir, '..', 'Data', 'disease_table.json'), 'r') as file:
        data = json.load(file)
    return render_template("index.html", disease_data=data)
    
@views.route("/loading", methods=["POST"])
def loading():
    if request.method == "POST":

        # identify what form was submitted
        form_id = request.form.get('form_id')

        if form_id == "form1":

            session.clear()

            # start with new database on every run
            resetDatabase()

            # get all user input
            session["disease-name"] = request.form.get("disease-name")
            session["disease-id"] = request.form.get("disease-id")
            session["num-processes"] = int(request.form.get("num-processes"))
            session["email"] = request.form.get("email")
            session["api-key"] = request.form.get("api-key")
            session["remove-terms"] = request.form.get("remove-terms")

            # add the user's API-Key for the session
            if not session["api-key"] == "":
                subprocess.run(f'export NCBI_API_KEY={session["api-key"]}', shell=True)

            # get a list of protein's amino acids from the inputted disease-id
            if not session["disease-id"] == "":  
                print("disease-id" in session)
                print(session["disease-id"])
                breakpoint()
                session["aa_seqs"] = protein_extactor(session["disease-id"])
                session["num_seqs"] = len(session["aa_seqs"])

            # TO TEST THE MODEL
            session["model"] = True

            return render_template("loading.html", load_type = "disease", disease_name = session["disease-name"])
        
        elif form_id == "form2":
            session["associated-disease"] = request.form.get("associated-disease")

            return render_template("loading.html", load_type = "disease", disease_name = session["associated-disease"])
        
        elif form_id == "w2v":
            session["word2vec_term"] = request.form.get("w2v-disease")

            return render_template("loading.html", load_type = "w2v", prediction_term = session["word2vec_term"])
        
        elif form_id == "drug-profiles":
            session["profiles"] = True
            
            return render_template("loading.html", load_type = "drug-profiles", disease_id = session["disease-id"])
 

@views.route("/data", methods=["POST", "GET"])
def data():
    if "profiles" in session:

        drug_profiles = generateDrugProfiles([item.term for item in cosineSimilarity.query.all()], session["disease-id"])

        return render_template("data.html", data_type = "drug-profiles",
                               drug_profiles=drug_profiles)

    elif "word2vec_term" in session:

        runWord2Vec(session["word2vec_term"])

        return render_template("data.html", data_type = "w2v",
                                prediction_term = session["word2vec_term"],
                                w2v_terms = cosineSimilarity.query.all())

    elif "associated-disease" in session:

        getLitData(session["associated-disease"], int(session["num-processes"]), session["email"], session["remove-terms"])

        return render_template("data.html", 
                        data_type="associated-disease",
                        compounds=compoundScoringData.query.filter_by(search=session["associated-disease"]), 
                        features=featureScoringData.query.filter_by(search=session["associated-disease"]), 
                        diseases=associatedDiseases.query.filter_by(search=session["associated-disease"]),
                        abstracts=queryData.query.filter_by(search=session["associated-disease"]).first())
    
    elif "disease-name" in session:

        getLitData(session["disease-name"], int(session["num-processes"]), session["email"], session["remove-terms"])

        return render_template("data.html",
                            data_type="original-disease",
                            compounds=compoundScoringData.query.filter_by(search=session["disease-name"]), 
                            features=featureScoringData.query.filter_by(search=session["disease-name"]), 
                            diseases=associatedDiseases.query.filter_by(search=session["disease-name"]),
                            abstracts=queryData.query.filter_by(search=session["disease-name"]).first())
        
    else:
        error_message = "No disease name defined, please return to home page."
        return render_template("error.html", message = error_message)
         

@views.route("/tutorial")
def tutorial():
    return render_template("tutorial.html")

website/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='styles.css')}}">
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.13.6/css/jquery.dataTables.css">
</head>
<body>
    <header>
        <a href="{{url_for('views.home')}}"><h2>DrugSift</h2></a>
        <div class="header-buttons">
            <a href="{{url_for('views.tutorial')}}"><button>Tutorial</button></a>
        </div>
    </header>
    <div id="content">
        {% block content %}
        {% endblock %}
    </div>
    <footer>
        <p>Created by Caleb Wang and Ayush Pinnamaraju</p>
    </footer>
</body>
    {% block script %}
    {% endblock %}
    </html>

website/templates/data.html
{% extends "base.html" %}

{% block title %}Data{% endblock %}

{% block content %}

    {% if data_type == "original-disease" or data_type == "associated-disease" %}
        <div class="data-heading">
            <h1>Data Summary</h1>
            <p>Number of Abstracts Retrieved: {{abstracts.retrieved}}</p>
            <p>Number of Abstracts Available: {{abstracts.total}}</p>
        </div>
        


        <h2>Extracted Compounds</h2>
        <p><em>May contain noise</em></p>
        <div class="table-container" id="output-table">
            <table id="compounds" class="display" style="width:100%">
                <thead>
                    <tr>
                        <th>Term</th>
                        <th>TF-IDF Score</th>
                    </tr>
                </thead>
                <tbody>
                    {% for compound in compounds %}
                        <tr>
                            <td>{{compound.compound_term}}</td>
                            <td>{{compound.tfidf_score}}</td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>

        <h2>Extracted Features</h2>
        <p><em>May contain noise</em></p>
        <div class="table-container" id="output-table">
            <table id="features" class="display" style="width:100%">
                <thead>
                    <tr>
                        <th>Term</th>
                        <th>TF-IDF Score</th>
                    </tr>
                </thead>
                <tbody>
                    {% for feature in features %}
                        <tr>
                            <td>{{feature.feature_term}}</td>
                            <td>{{feature.tfidf_score}}</td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>

        <h2>Associated Diseases</h2>
        <p><em>May contain noise</em></p>
        <div class="table-container" id="output-table">
            <table id="diseases" class="display" style="width:100%">
                <thead>
                    <tr>
                        <th>Term</th>
                        <th>Frequency</th>
                    </tr>
                </thead>
                <tbody>
                    {% for disease in diseases %}
                        <tr>
                            <td>{{disease.disease_term}}</td>
                            <td>{{disease.frequency}}</td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
        {% elif data_type == "w2v" %}
        <div class="data-heading">
            <h1>Word2Vec Summary</h1>
        </div>
        <div class="table-container" id="output-table">
            <table id="diseases" class="display" style="width:100%">
                <thead>
                    <tr>
                        <th>Term</th>
                        <th>Cosine Similarity</th>
                        <th>Corpus</th>
                    </tr>
                </thead>
                <tbody>
                    {% for term in w2v_terms %}
                        <tr>
                            <td>{{term.term}}</td>
                            <td>{{term.cosine_similarity}}</td>
                            <td>{{term.corpus}}</td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
        {% elif data_type == "drug-profiles" %}

        <div class="data-heading">
            <h1>Drug Profile Summary</h1>
            <p>Number of drugs listed: {{len(drug-profiles)}} </p>
        </div>

        <div class="profile-container">
            {% for drug in drug-profiles %}
                <div class="drug-profile">
                    <img class="drug-image" src="https://www.ebi.ac.uk/chembl/api/data/image/{{ drug['chembl_id'] }}" alt="Molecule Image">
                    <div class="drug-overview">
                        <h1>{{drug["name"]}}</h1>
                        <h2>{{drug["Formula"]}}</h2>
                        <h3>ChEMBL ID: {{drug["chembl_id"]}}</h3>
                    </div>
                </div>
            {% end for %}
            <dialog>
                <div class="dialog-content">

                </div>
            </dialog>
        </div>


    {% endif %}

    {% if data_type == "original-disease"%}
        <div class="disease-container">
            <h2>Select an Associated Disease</h2>
            <p>Repeats Text Mining</p>
            <form id="disease-selection" action="{{ url_for('views.loading') }}" method="post">
                <input type="hidden" name="form_id" value="form2">
                <label for="disease-name">Disease Name</label>
                <input type="text" id="disease-name" name="associated-disease" placeholder="venous thrombosis">
                <button type="submit">Start Pipeline</button>
            </form>

        </div>
    {% elif data_type == "associated-disease" %}
        <div class="disease-container">
            <h2>Train Word2Vec Model</h2>
            <p>Create associations between terms</p>
            <form id="disease-selection" action="{{ url_for('views.loading') }}" method="post">
                <input type="hidden" name="form_id" value="w2v">
                <label for="disease-name">Prediction Term</label>
                <input type="text" id="disease-name" name="w2v-disease" placeholder="venous thrombosis">
                <button type="submit">Train Model</button>
            </form>
        </div>

    {% elif data_type == "w2v" %}
        <div class="disease-container">
            <h2>Use SSM-DTA and ADMET AI</h2>
            <p>Get Drug Profiles</p>
            <form id="disease-selection" action="{{ url_for('views.loading') }}" method="post">
                <input type="hidden" name="form_id" value="drug-profiles">
                <button type="submit">Use Model</button>
            </form>
        </div>
    {% elif data_type == "drug-profiles" %}

    {% endif %}


    
    


    <script src="https://code.jquery.com/jquery-3.7.0.min.js"></script>
    <!-- DataTables JS -->
    <script src="https://cdn.datatables.net/1.13.6/js/jquery.dataTables.min.js"></script>

    <script src="../static/table.js"></script>
    <script src="../static/script.js"></script>
{% endblock %}

website/templates/error.html
{% extends "base.html" %}

{% block title %}Error{% endblock %}

{% block content %}
    <h1>Oops! Something went wrong..</h1>
    <h2>Error Message:</h2>
    <p>{{message}}</p>
{% endblock %}

website/templates/index.html
{% extends "base.html" %}

{% block title %}Home{% endblock %}

{% block content %}

        <div class="main-content">
            <div class="heading">
                <h1>Discover Drug Repurposing Candidates</h1>
                <h3>Powered by natural language processing and deep learning</h3>
            </div>
            <form id="basic-search" action="{{ url_for('views.loading') }}" method="post">
                <input type="hidden" name="form_id" value="form1">
                <label for="disease-name">Disease Name</label>
                <input type="text" id="disease-name" name="disease-name" placeholder="venous thrombosis">
                <label for="disease-id">Disease ID</label>
                <input type="text" id="disease-id" name="disease-id" placeholder="DI-00127">
                <button type="submit">Start Pipeline</button>
            </form>
            <p>Advanced</p>
            <dialog>
                <div class="dialog-content">
                    <svg id="dialog-close" xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="#" stroke-width="3" stroke-linecap="round" stroke-linejoin="round" class="feather feather-x"><line x1="18" y1="6" x2="6" y2="18"></line><line x1="6" y1="6" x2="18" y2="18"></line></svg>
                    <form id="advanced-search" action="{{ url_for('views.loading') }}" method="post">
                        <input type="hidden" name="form_id" value="form1">
                        <label for="disease-name">Disease Name</label>
                        <input type="text" id="disease-name" name="disease-name" placeholder="venous thrombosis">
                        <label for="disease-id">Disease ID</label>
                        <input type="text" id="disease-id" name="disease-id" placeholder="DI-00127">
                        <div class="horizontal-container">
                            <div class="advanced-inputs">
                                <label for="num-processes">Multiprocessing</label>
                                <input type="text" id="num-processes" name="num-processes" placeholder="Number of Processes">
                            </div>
                            <div class="advanced-inputs">
                                <label for="email">Email</label>
                                <input type="text" id="email" name="email" placeholder="researcher@lab.edu">
                            </div>
                        </div>
                        <label for="api-key">NCBI API Key</label>
                        <input type="text" id="api-key" name="api-key" placeholder="required to use EDirect">
                        <label for="remove-terms">Remove Terms</label>
                        <input type="text" id="remove-terms" name="remove-terms" placeholder="terms to remove from results">
                        <button type="submit">Start Pipeline</button>
                    </form>

                </div>
            </dialog>
        </div>

        <div class="body-content">
            <div class="uniprot-heading">
                <h1>Search UniProt</h1>
                <h3>Selected Diseases' Associated Proteins Used as Targets</h3>
            </div>
    
            <div class="table-container">
                <table id="uniprot" class="display" style="width:100%">
                    <thead>
                        <tr>
                            <th>DiseaseID</th>
                            <th>Name</th>
                            <th>Keywords</th>
                            <th>Alternative Names</th>
                            <th>Description</th>
                            <th>Mnemonic</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for disease in disease_data %}
                            <tr>
                                <td>{{disease['DiseaseEntryID']}}</td>
                                <td>{{disease['Name']}}</td>
                                <td>{{disease['Keywords']}}</td>
                                <td>{{disease['Alternative Names']}}</td>
                                <td>{{disease['Description']}}</td>
                                <td>{{disease['Mnemonic']}}</td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
        
        <script src="https://code.jquery.com/jquery-3.7.0.min.js"></script>
        <!-- DataTables JS -->
        <script src="https://cdn.datatables.net/1.13.6/js/jquery.dataTables.min.js"></script>

        <script src="../static/table.js"></script>
        <script src="../static/script.js"></script>
{% endblock %}

website/templates/loading.html
{% extends "base.html" %}

{% block title %}Loading{% endblock %}

{% block content %}
    {% if load_type == "disease" %}
        <div class="loading-container">
            <h1>Pipeline Working</h1><br>

            <h2>Getting data for</h2>
            <p>{{disease_name}}</p>
        
            <div class="lds-ellipsis"><div></div><div></div><div></div><div></div></div>
        </div>

    {% elif load_type == "w2v" %}
        <div class="loading-container">
            <h1>Word2Vec Model Training</h1><br>

            <h2>User Prediction Term</h2>
            <p>{{prediction_term}}</p>
        
            <div class="lds-ellipsis"><div></div><div></div><div></div><div></div></div>
        </div>
    {% elif load_type == "drug-profiles" %}
        <div class="loading-container">
            <h1>Generating Drug Profiles</h1><br>

            <h2>Inputted UniProt ID</h2>
            <p>{{disease_id}}</p>
        
            <div class="lds-ellipsis"><div></div><div></div><div></div><div></div></div>
        </div>
    {% endif %}
    
    

{% endblock %}

{% block script %}
    <script>window.location.href = "{{ url_for('views.data') }}"</script>
{% endblock %}

website/templates/tutorial.html
{% extends "base.html" %}

{% block title %}Tutorial{% endblock %}

{% block content %}
    <h1>Welcome to the tutorial!</h1>
{% endblock%}